stages:
  - build
  - deploy

variables:
  REMOTE_PATH: /home/ubuntu/shpp/java-backend/project-1

cache:
  key: maven
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.8-eclipse-temurin-17
  script:
    - mvn clean package -Passembly
    - mvn package -Pshade
  artifacts:
    paths:
      - target/*.jar
      - target/lib/

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$EC2_SSH_KEY" > key.pem
    - chmod 600 key.pem
    - ssh-add key.pem
  script:
    - scp -o StrictHostKeyChecking=no target/*.jar $EC2_USER@$EC2_HOST:$REMOTE_PATH
    - scp -o StrictHostKeyChecking=no -r target/lib $EC2_USER@$EC2_HOST:$REMOTE_PATH/